"""modules/pc_control/base.py — Interfaccia astratta PC Control"""
from abc import ABC, abstractmethod
from pathlib import Path

class BasePCControl(ABC):
    @abstractmethod
    def open_application(self, app_name: str) -> bool: ...
    @abstractmethod
    def open_file(self, path: Path) -> bool: ...
    @abstractmethod
    def type_text(self, text: str) -> None: ...
    @abstractmethod
    def take_screenshot(self) -> bytes: ...
    @abstractmethod
    def list_open_windows(self) -> list[str]: ...
    @abstractmethod
    def read_clipboard(self) -> str: ...
    @abstractmethod
    def write_clipboard(self, text: str) -> None: ...
