"""modules/speaker_id/base.py — Interfaccia astratta Speaker ID"""
from abc import ABC, abstractmethod
from core.context import SpeakerInfo

class BaseSpeakerID(ABC):
    @abstractmethod
    def identify(self, audio: bytes, sample_rate: int = 16000) -> SpeakerInfo: ...
    @abstractmethod
    def enroll(self, speaker_id: str, display_name: str, audio: bytes) -> None: ...
    @abstractmethod
    def remove(self, speaker_id: str) -> None: ...
    @abstractmethod
    def list_speakers(self) -> list[dict]: ...
    @abstractmethod
    def is_ready(self) -> bool: ...
